### ISSUE TITLE
Links with two or more underscores are masked with <em></em> tag

### ISSUE THREAD

**Issue by haimich** [michelf/php-markdown#126]
We use the library to generate html out of markdown for our RSS feeds. We recently received a bug report that a certain link wasn't displayed correctly in the feed - after some research we found out that links like 

http://www.google.de/a_nice_link/index.html

will become

http://www.google.de/a<em>nice</em>link/index.html

after transformation. If you find some time we'd appreciate you having a look after this. Thanks!

**Comment by michelf** [comment]
Actually the Markdown syntax requires links to be put inside angle brackets like this `<http://domain/path>`. If you get a link without the angle brackets, something else than PHP Markdown is making it a link.

PHP Markdown mimics the behavior of the original Markdown parser, accepting underscores inside words to mean italic. (Your link is seen as plain text since it is not surrounded by angle brackets.) If you don't want underscores inside words to mean italic, use the Markdown Extra parser.

**Comment by haimich** [comment]
Thanks a lot for your fast response, I didn't know this was part of the MD syntax. We will try out the Markdown Extra parser or surround the links with < > when entered in our frontend.
