### ISSUE TITLE
Coding standards and phpdoc

### ISSUE THREAD

**Issue by lsolesen** [michelf/php-markdown#2]
I would volunteer to run php-markdown through

```
phpcs
```

to have it adhere to some common coding standards and make the inline documentation compatible with phpdoc.

Would you accept pull requests on that?

**Comment by michelf** [comment]
Hum, can you elaborate on the benefits?

The benefit of the current style is that it matches as much as possible the style of the original Markdown in Perl, which makes it easy to compare with and port changes.

That said, John Gruber's Markdown.pl hasn't been updated since a long time, so it might not be much of a problem any longer. But I'm not too sure of the benefits it'd bring.

I also worry about breaking PHP 4 compatibility (even though I know PHP 4 is obsolete, many people still use it), which makes it harder to follow more modern standards. The benefits would need to be really worth it for me to be willing to break PHP 4 compatibility.

**Comment by lsolesen** [comment]
The benefits would just be, that the code looked like code in a lot of other projects, like Doctrine, PEAR, Symfony, Zend etc. And would maybe be a bit easier to read? Also making the changes would make it possible to automatically generate api documentation of the classes.

It would not break PHP to rewrite the inline docs in the parser to phpdoc style.

**Comment by michelf** [comment]
You talk about "coding standards" and documentation comments, which to me are two different things. I'm not opposed to using a different style of documentation comments. But changing the coding standard (spaces around brackets, tabs, indentation, etc.) just so it looks more like some other project doesn't seem a very compelling reason.

**Comment by lsolesen** [comment]
That is allright. Just wanted to ask whether you wanted the project to adhere to PHP_CodeSniffer standards.

**Comment by itafroma** [comment]
I think the coding standards issue is somewhat moot (although there's now a more formal "recommendation" in the form of PSR-2), but there are some tangible benefits to adopting PHPDoc-style commenting beyond conformance:
- Most PHP IDEs recognize PHPDoc-style tags for the purposes of code sensing
- Since it's a dialect of Javadoc, API documentation generators, ranging from doxygen to PHPDocumentor, generally all recognize PHPDoc-style tags.

So, putting aside the other aspects of coding standards, I'd like to extend the offer I made in #98 to create a PR to convert just the comments if you're amenable to it, @michelf.
