### ISSUE TITLE
Availability on bower.io

### ISSUE THREAD

**Issue by vaughany** [michelf/php-markdown#201]
Just a short one: is it possible you could make this project available to install via Bower (http://bower.io/)?  

Cheers!

**Comment by vaughany** [comment]
Ugh, didn't see it on the website but 'bower search' located it immediately. Sorry for the noise.

**Comment by michelf** [comment]
Intriguing. Perhaps Bower can install Composer packages found on https://packagist.org automatically, or perhaps someone forked and made it into a Bower package. What I do know is that there is no configuration file for Bower in this repository.

**Comment by standaniels** [comment]
I may be wrong, but isn't Bower meant for client side programming?

**Comment by vaughany** [comment]
@standaniels It's a package manager, so I've used it previously to get (and keep up-to-date) jQuery, Bootstrap, Font Awesome, various JS libraries etc.  As I'm adding markdown support to my project, I'll use it to keep track of PHP markdown too.

**Comment by standaniels** [comment]
According to Wikipedia [Bower is a package management system for client-side programming](http://en.m.wikipedia.org/wiki/Bower_%28software%29) and [Composer is an application-level dependency manager for the PHP programming language](http://en.m.wikipedia.org/wiki/Composer_%28software%29).

Since php markdown is a php package it should be managed by Composer, in my honest opinion.
