### ISSUE TITLE
Broken semantic versioning in version 1.5.1

### ISSUE THREAD

**Issue by michelf** [michelf/php-markdown#218]
Looks I was a bit to hasty with the last release. To respect semantic versioning, it should have version number 1.6.0, not 1.5.1. Now that it has been pushed, I'm not sure I can really "unpush" it.

**Comment by Reconix** [comment]
shh, quickly change the version numbers, no one will notice, they're all too busy getting ready for Santa !

**Comment by michelf** [comment]
I should probably do that, and remove the 1.5.1 tag from the repository. I'm mostly worried that packagist.org won't notice the version tag has disappeared because git doesn't propagate tag deletions, and that it'll remain there (and anywhere else that automatically tracks the repo) in perpetuity.

**Comment by michelf** [comment]
Just released 1.6.0 and I also removed the 1.5.1 tag. It looks like Packagist understands tag removals because 1.5.1 is no longer [listed](https://packagist.org/packages/michelf/php-markdown). Merry Christmas @Reconix.

**Comment by Reconix** [comment]
Yes, I see your predicament, never the less, everyone really appreciates the work you and the contributors put into Markdown. 
Main issue, can I see in the Changelog, a quick glance of what's gone on ? Can I see code highlights of what's changed or added ? YES !
Ok, wrong versions I'll let slide because of the great work done by everyone.

and Merry Christmas btw !
