### ISSUE TITLE
Bug in Multiple References of the Same Footnote

### ISSUE THREAD

**Issue by taufik-nurrohman** [michelf/php-markdown#221]
When writing multiple footnotes for the same reference, I got this weird reference ID pattern. Is this valid?
#### Example

``` .markdown
Lorem ipsum [^1] dolor sit amet [^2]

Lorem ipsum [^1] dolor sit amet [^2]

[^1]: Footnote 1
[^2]: Footnote 2
```
#### Footnote Output
1. Footnote 1 [↩]() [↩]()
2. Footnote 2 [↩]() [↩]()
#### Hash Produced

``` .no-highlight
#fnref:1
#fnref2:1

#fnref:2
#fnref2:2
```

Why not produce this instead?

``` .no-highlight
#fnref:1
#fnref:1-2

#fnref:2
#fnref:2-2
```

or &hellip;

``` .no-highlight
#fnref:1
#fnref-2:1

#fnref:2
#fnref-2:2
```

**Comment by michelf** [comment]
What makes you think it might not be valid? Is the current output causing some problems for you?

**Comment by taufik-nurrohman** [comment]
Namespace consistency in the fragment identifier. Changing the fragment identifier prefix will break the flow.

Example: http://csswizardry.com/2011/06/namespacing-fragment-identifiers/

**Comment by michelf** [comment]
Interesting. That's the first time I see an article about namespacing fragment identifiers in HTML.

Footnotes came to PHP Markdown Extra in 2006 with the format `fnref:id`. Then in 2013 they gained the ability of having multiple references. While it seems logical that you'd simply append `-2` at the end of the footnote id, that's not safe because the user has control of the second part of the footnotes ids. I could write this:

```
Reference to this[^someid] and that[^someid-2].
Reference to this[^someid] and that[^someid-2].
[^someid]: blah
[^someid-2]: blah
```

... and the generated back reference ids would clash. That's why the `2` has to be added before the colon for the second back reference. And if you add it before the colon, what difference does it makes whether there is a dash or not?

Anyway, I'm not going to change what PHP Markdown does by default since it'd break existing links everywhere.
