### ISSUE TITLE
Can't convert markdown codes which be contained in HTML tags

### ISSUE THREAD

**Issue by hidehalo** [michelf/php-markdown#242]
Here is the origin code:

> `<h3 style="text-align: center;">
>   <b style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;, Times;">
>       Test
>   </b>
> </h3>`

And I use tool convert origin codes to markdown:

> `<font color="#000000" face="Courier New, Courier">**Test**</font>`
## php-markdown can't transform those codes,the result is same.

Is there a way to skip convert the HTML tags, and converted the markdown codes which into HTML tags ?

**Comment by michelf** [comment]
It'd be easier to help if you could tell me a bit more:
1. What is the Markdown input?
2. What is the output you got?
3. What is the output you expected?

**Comment by hidehalo** [comment]
@michelf 
1.Markdown input:
`<font color="#000000" face="Courier New, Courier">**Test**</font>`
2.Output I got:
`<font color="#000000" face="Courier New, Courier">**Test**</font>`
3.What is the output I expected?
`<h3 > <b style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;, Times;"> Test </b> </h3>`

**Comment by michelf** [comment]
- There is no reason to expect an `<h3>` to appear in the output since you aren't using any header syntax in the input.
- Markdown isn't designed to change the `<font>` tag and transform it to a `style` attribute. I'm not sure why you are expecting that.
- The `**` correctly becomes `<strong>` in my testing. I'm not sure why it doesn't for you. Have you omitted parts of the input? This is the output I get on the [PHP Markdown Dingus](https://michelf.ca/projects/php-markdown/dingus/):
  
  ```
  <p><font color="#000000" face="Courier New, Courier"><strong>Test</strong></font></p>
  ```

**Comment by hidehalo** [comment]
I use html-to-markdown lib convert html to markdown for stored ,and use php-markdown transformed.thx for ur asking,maybe my idea is bad.
