### ISSUE TITLE
Footnotes created are not epub valid

### ISSUE THREAD

**Issue by 1manfactory** [michelf/php-markdown#253]
When generating footnotes (which looks ok and behave ok) I get this kind of ids

`#fn:1`

Those are not valid XML ids. Hence epub validation fails with:

> Error while parsing file 'value of attribute "id" is invalid; must be an XML name without colons

**Comment by michelf** [comment]
Is there such a thing as an "xml ID"? It might not be valid for epub, I do not know. It'd help to know which part of which spec is being violated and which validator is used to detect this.

As far as I can tell, using the colon is valid for the id attribute in HTML and XHTML according to the W3C validator.

**Comment by 1manfactory** [comment]
Sorry for not providing the info. I thought this was common.

[https://github.com/IDPF/epubcheck/releases/tag/v4.0.1]

This is the standard epub validation check for the publishing industry.

**Comment by michelf** [comment]
The main question I'm interested in is: is this a bug in the validator, or is it the epub spec that is more restrictive than HTML. I don't really have the time nor the inclination to investigate this though.

I'm not even sure what can be done if gets confirmed that the epub spec forbids this because changing it at this point could mean breaking links that exists on many web pages. Anyway, without the answer to the above question trying to figure out what to do is a bit premature.

**Comment by 1manfactory** [comment]
I understand your concerns about fiddling around in the code for this.

But for me epub validation it's essential. They might be strict about this maybe because some old epub reading devices are not able to handle this - who knows?

All I know is that the way you handle footnotes is not valid in industrial standard.

I just deleted the colons manually - result: valid.

I already programmed a function "searchAndReplaceInzip" to handle all this little "bugs" which are generated but invalid afterwards.

Also your back arrow is difficult to handle. It is valid but some devices are not able to display them, they just show an empty little square. I use my little function as well to replace them with " <<<" which is also easier to press with plumb fingers :-)

**Comment by 1manfactory** [comment]
For those of you interested. This is how I handle the issues mentioned above after! HTML ist generated. Then epub validation is ok.

```
$html=preg_replace('/id="(\w+?):(\d+?)"/u', 'id="$1$2"', $html);
$html=preg_replace('/href="#(\w+?):(\d+?)"/u', 'href="#$1$2"', $html);
$html=preg_replace('/&#8617;&#xFE0E;/u', '&lt;&lt;&lt;', $html);
```

**Comment by michelf** [comment]
For the backlink arrow, you might be interested in setting the `fn_backlink_html` variable of the parser object to something else.

**Comment by michelf** [comment]
With the information I have, it it looks likely to be a bug in the validator. There is no requirement in HTML about the content of the `id` attribute except that it must contain no space. See the [WHATWG HTML Living standard](https://html.spec.whatwg.org/#the-id-attribute) or the [W3C HTML 5.1](https://www.w3.org/WebPlatform/docs/html51/dom.html#the-id-attribute) specification.

Even if for some reason someone decides it needs to follow the [ID validity constraint from the XML spec](https://www.w3.org/TR/REC-xml/#id), the constraints then is that that it much match the `Name` production were a colon is permitted.

It looks like the reason the validator rejects the colon is that it uses the XSD datatype ID definition, which is defined to follow the `NCName` rule (name with no colon) instead of using the `Name` rule (per the XML spec) or the no-space rules in HTML. Perhaps there is a deeper or more valid reason I don't know about, but to me it looks like it's done that way because it's more convenient to implement it that way in the validator, if I read this issue well: https://github.com/IDPF/epubcheck/issues/224

I realize that in the end, you probably don't care about whose bug this is, as long as you can produce an epub file that validates. Post-processing the HTML generated by PHP Markdown seems like a good workaround.
