### ISSUE TITLE
<ol> start Attribute not allowed in EPUBS

### ISSUE THREAD

**Issue by 1manfactory** [michelf/php-markdown#257]
I know, you gonna hate me. It's me again.

This is a highly disputed point in epub generating. Ordered lists with start attributes are simply not allowed - no matter how handy they come.

Right now I "simply" escape every dot and parenthesis after figures to stop markdown from detecting it as a list.

Do you know any smarter way?

**Comment by michelf** [comment]
Can you share some sample input that produces a list with the start attribute?

**Comment by 1manfactory** [comment]
`10. June`

makes

```
<ol start="10">
<li>June</li>
</ol>
```

Which is simply not valid as epub

> sec000007.xhtml(15,16): Error while parsing file 'attribute "start" not allowed here; expected attribute "class", "dir", "id", "lang", "style", "title" or "xml:lang"'

**Comment by michelf** [comment]
There is not enough context in your sample for me to recommend another solution than escaping the dot with a backslash. It's possible there is a better solution, but I can't tell from what you are showing me.

You also haven't told me whether emitting an `<ol>` is what you want or not, only that you don't want the `start` attribute.

I mean, if you only care about the `start` attribute not being there, you could go back to PHP Markdown Lib 1.4.1 since at that time the attribute wasn't supported. But then what you'd get in the output is an ordered list with no `start` attribute that would show up as item number "1" when the HTML is rendered. Am I right that this is not what you want?

**Comment by jerry1970** [comment]
I think epub should get their parsing straight, since the HTML is valid and this is a Markdown to HTML parser. Issue closed?

**Comment by 1manfactory** [comment]
Do as you want.
I already escape this by regex to avoid this behavior.
Close it or not. I don't care.
