### ISSUE TITLE
Don't transform to a header if no space after #

### ISSUE THREAD

**Issue by edhelas** [michelf/php-markdown#275]
Is it possible to disable the title configuration if there is no space between the # and the first character of the title? In some cases people are declaring hashtags this way.

See https://github.com/jupyter/notebook/issues/474, http://www.cirosantilli.com/markdown-style-guide/#option-header-atx and https://daringfireball.net/projects/markdown/basics

**Comment by michelf** [comment]
The space has been optional since the first implementation of Markdown, from which PHP Markdown is derived. Changing that now would break so many documents everywhere.

I'm actually surprised at the number of Markdown implementations that don't accept this as a header. http://johnmacfarlane.net/babelmark2/?normalize=1&text=%23header

The best that could be done is to add another configuration variable for this in the parser. I'm not too sure how useful that would be.

**Comment by edhelas** [comment]
I'm fine with a small configuration to trigger those title only if there's a space after the # , thanks :)

**Comment by edhelas** [comment]
Hello, I'm planning to release a new version of my project in the upcoming weeks, do you know if this little configuration variable could be added before that? Thanks :)

**Comment by michelf** [comment]
I don't know. But feel free to make a pull request if you implement it.
