### ISSUE TITLE
Where is PHP Markdown Extra

### ISSUE THREAD

**Issue by lsolesen** [michelf/php-markdown#3]
Once upon a time PHP Markdown Extra was also included in the markdown.php file. Where has it gone?

**Comment by michelf** [comment]
Look at the "extra" branch, you'll find this file:
https://github.com/michelf/php-markdown/blob/extra/markdown.php

**Comment by lsolesen** [comment]
Why is it only in a branch and not in master?

**Comment by michelf** [comment]
Because I'm maintaining the two in parallel. I could have created a second repo for it but I didn't feel like it was worth the complication. If the only difference in Extra was the presence of a second class for the Extra parser this wouldn't be needed, but there are other changes to maintain. It also makes it easier to maintain the version history in sync in the readme files. Diff the two branches and you'll see.

If you look at the [tree graph](https://github.com/michelf/php-markdown/network) (or if you use gitk at the command line to get a tree view) you'll see that I do changes to PHP Markdown on the master branch, then I merge the master branch in the extra branch whenever I need it. It works well.

**Comment by lsolesen** [comment]
Couldn't you refactor so you did not have to maintain two different branches?

**Comment by michelf** [comment]
I gave it a lot of thought when switching to the object-oriented design.

The basic problem is that people are relying on a global `Markdown` function to be available, which is mapped to the `Markdwon_Parser` or `MarkdownExtra_Parser` class depending on which package you downloaded. Most people use the global `Markdown` function, so I can't remove it without much disturbance. Many simply download

See this old message on the Markdown mailing list about how it works:
http://six.pairlist.net/pipermail/markdown-discuss/2006-May/000054.html

Actually, I don't really have to maintain two separate branches, I only maintain two separate parser classes (hosted in the same file), one of which derives from the other. I'm keeping them in separate branches because it mirrors how things are packaged and also because git makes it easy to keep things in sync.

Sure, I _could_ refractor all this, but why _should_ I? I'm not opposed to refactoring if it improves things and it stays easy to create the release packages. Which kind of refactoring would you like to see?
