### ISSUE TITLE
PEAR Repository Information Misleading

### ISSUE THREAD

**Issue by jnovack** [michelf/php-markdown#50]
This isn't specifically php-markdown related, but it does affect it.

According to your homepage, your pear statement is `pear channel-discover pear.michelf.ca`  However, according to `http://pear.michelf.ca/channel.xml` the baseurl is `http://pear.michelf.com/`

This causes an error when attempting to channel-discover `pear.michelf.ca` twice or attempting to see if `pear.michelf.ca` exists as a channel.  Notice that **pear.michelf.com** was added.

```
# pear channel-discover pear.michelf.ca
Adding Channel "pear.michelf.com" succeeded
Discovery of channel "pear.michelf.ca" succeeded
# pear channel-discover pear.michelf.ca
Discovery of channel "pear.michelf.ca" failed (channel-add: Channel 
"pear.michelf.com" exists, use channel-update to update entry)
```

**Comment by michelf** [comment]
Hum, looks like this was only half-moved when I moved my site to the .ca domain. Currently, the pear channel is available on both domains, and I wonder if there is a clean way to migrate it from one to the other without breaking things for anyone.

**Comment by jnovack** [comment]
It is available from both, as I can `pear channel-discover` to both domains, however, because the `channel.xml` file says **pear.michelf.com**, it thinks the "real" domain is **pear.michelf.com**.

Why not make a play to submit to **pear.php.net**?  Once you lib it up, they probably would be happy to accept it from the original maintainer.  They have repos right here on github, all you need to do is push there.

**Comment by michelf** [comment]
Right now, maintaining three packages by merging changes between each other, two of those package being compatible all the way back to PHP 4, while trying to adhere to PEAR's coding standard is not an exercise I want to try. Beside, if pear.php.net wants everything in a PEAR2 namespace, that'd make it a fourth package to maintain.

**Comment by michelf** [comment]
I realize I shouldn't have tried to change the domain to .ca in the first place: it causes problems because the domain name is too well rooted in every file, including package archives, and because there is no transition path for those who were using the old domain.

I could fix it by creating two channels, but that'd be too complicated (I did try). So I reverted the channel domain back to pear.michelf.com, because it seems like the pear.michelf.ca channel never really worked. Should work fine now, but you might have to make pear forget and rediscover the channel.
