### ISSUE TITLE
Make `detab` optional

### ISSUE THREAD

**Issue by lorenzos** [michelf/php-markdown#74]
Is it possible to provide an option to avoid tabs from being converted into spaces in code block?

Sometimes I just want my code to be formatted with _real_ tab characters.

**Comment by michelf** [comment]
Unfortunately, no. Almost every regex in the parser expects spaces, and counts them. That's why tabs are converted to spaces early in the process.

It should be possible to convert spaces to tabs after the parser has done its work, but such an option won't preserve the actual input if it was made of spaces.

**Comment by lorenzos** [comment]
In fact, I suspected _tabs to spaces_ got something to do with the rest of the markdown parsing. I will search a way to do a _spaces to tabs_ **after** the parsing, also if a little tricky because I had to intercept only multiple groups of four spaces at the beginning of lines (if you want to help me ;)...

**Comment by michelf** [comment]
Perhaps this:

``` php
$with_tabs = preg_match_callback('/^((?:[ ]{4})+)/m', function($match){
    return str_repeat("\t", strlen($match[1])/4);
}, $with_spaces);
```

**Comment by lorenzos** [comment]
I was un-aware of `?:` for non-captured groups. Thank you.
