### ISSUE TITLE
Ability to create custom filters (e.g. link filter)

### ISSUE THREAD

**Issue by xPaw** [michelf/php-markdown#85]
(from issue #82)

**Comment by aoloe** [comment]
i'm interested in working on this.
mostly to allow something like https://pypi.python.org/pypi/markowik 's image-baseurl.

my goal is to add a prefix to all local url, both for images and for links.
do you think that it can be solved with filters?

do you already have an idea, how and where custom filters should be implemented?

otherwise, i can imagine that implementing it in a similar way as `$parser->fn_id_prefix` would be a simpler fix for me...
i would go for `url_href_prefix` (for all local paths), `url_a_prefix` (only for links), and `url_img_prefix` (only for images).

**Comment by michelf** [comment]
The way I see it, there should be a `url_filter_func` configuration variable that contains something callable. It should contain a function name string, an array with an object and a method name, an anonymous function, or a closure (available with PHP 5.4). Whenever the parser has to emit some HTML that contains a URL, it calls `url_filter_func` this way:

```
$url = call_user_func($this->url_filter_func, $url);
```

to get the URL to emit in the HTML output. The default value of `url_filter_func` would be a reference to a function that checks for a `mailto:` scheme and obfuscate it with entity encoding (as discussed in #171). Someone who wants to change the default behaviour can set `url_filter_func` with a function that does whatever he wants (adding a prefix, checking for XSS, ban domains, etc.).

**Comment by aoloe** [comment]
looks good!

thanks!

personally, i've spent my time checking what are my "real" needs and implemented a class wrapped around php-markdown.!
what i noticed, is that i need the option for different url transformation for local images and local urls.

i skimmed through your patch and it looks really straight forwards (which is a further compliment to you! :-): if at the end of the current project i'm still convinced that i need that separation, i'll make a patch and pull request (it should not be more than a dozen of lines of code...).

**Comment by markseuffert** [comment]
It looks promising, thanks!

I added the new custom filter to our CMS. I am no longer able to sneak in JavaScript into the generated output. Here's what I did: Enabled `no_markup` and `no_entities`, filtered all URLs via `url_filter_func` which checks for regular expression `/^javascript:/i`. Then we tried to inject HTML code with obfuscation and random data. So far it holds, but hard to tell how well it works. [Here's are some test cases](http://demo.datenstrom.se/tests/xss-filter).

The question is: is this enough to prevent XSS?

**Comment by michelf** [comment]
> The question is: is this enough to prevent XSS?

No. You should use use a whitelist, not a blacklist. With `/^javascript:/` as a filter, someone could entity-encode a character, or add a space before the scheme or another variant of malformed URL some browsers (not necessarily all) will accept. Use a whitelist.

**Comment by markseuffert** [comment]
The test cases check those things, [here's the Markdown](http://demo.datenstrom.se/edit/tests/xss-filter). :smile: 
Do you have an example that doesn't work?

**Comment by michelf** [comment]
> Do you have an example that doesn't work?

`vbscript:` URLs (IE-specific obviously). The problem is that attack vectors are sometime browser-specific, are generally undocumented and obscure things, and sometime depends on bugs in parsers, so the more you allow the bigger is the attack surface. So my advise is to use a whitelist. In other words you allow what you know is safe (at the risk of disallowing something safe) instead of disallowing what you know is unsafe (at the risk of allowing something unsafe).

**Comment by markseuffert** [comment]
Yes, you're right! Let's try a whitelist of schemes.

**Comment by markseuffert** [comment]
I am now testing whitelist `/^(http|https|ftp|mailto):/`, it's working better.
